### ISSUE TITLE
Not yet working fully with Debian bookworm PHP 8.2

### ISSUE THREAD

**Issue by kjohnsonecl** [ReimuHakurei/phpPgAdmin#12]
The version available here:

https://github.com/ReimuHakurei/phpPgAdmin/archive/refs/tags/v7.14.4-mod.tar.gz

does not yet fully work with Debian Bookworm that has PHP 8.2 installed from the default Debian package.  Viewing data appears to work fine, but attempting to modify data returns the "No unique identifier for this row." message.  FYI, in case you came here hoping for a fix for that to use in Debian Bookworm.

**Comment by ReimuHakurei** [comment]
Can you provide an example schema you are having this issue with?

**Comment by kjohnsonecl** [comment]
Thanks for your interest in this issue -- your response was unexpected -- I
had assumed that it didn't work because you hadn't worked on Bookworm yet,
and would get to it when you could.

Probably, if you tell me how.  I was working with a Mailman 3 database.  What
commands would I execute to generate a schema file that would address your
question?

I am recovering from a disk failure in my primary workstation so getting
that done may not happen right away.  Answering email is easy with my
secondary system; more complex tasks are tough right now.

Respectfully,

Ken

**Comment by ReimuHakurei** [comment]
I guess an easier question to ask is -- have you double-checked that there IS, in fact, a unique identifier for the table in question? (ie: a primary key or a column with a UNIQUE constraint)

Are you just viewing the table via Tables -> Browse, or is this in the result of a query? If via a query, the query result must contain some sort of unique identifier as well (ie: you must be SELECTing a UNIQUE or primary key column).

Are you using both PHP 8.2 and PostgreSQL installed from the standard Debian packaging?

**Comment by kjohnsonecl** [comment]
My primary workstation is sufficiently restored to get most work done.

The table in question is public.auth_user, in the mailman3web database (I think that is the default name for that database in Debian).  The first column displayed during a browse of the table is 'id'.  An examination of the columns showing type and constraints shows a key icon under Constraints for this column.  There are three entries in the table; the browse shows that these do have unique values of 2, 3, and 4.  So I think the answer is yes, there is a unique identifier, but I am far from a database expert and there may be subtleties I have overlooked.  It has happened.

Re PHP and Postgres:  Yes, both installed from standard Debian packaging.  However, the mailman databases are on Postgres 13; I have not yet upgraded to 15.  Perhaps that is the problem?  I was trying to get something fixed with Mailman that stopped working after the Bookworm upgrade -- it appears that Mailman is now fussier about unique email addresses, so I was going to change one.

PHP:

ii  php8.2                                       8.2.7-1~deb12u1                         all          server-side, HTML-embedded scripting language (metapackage)
ii  php8.2-apcu                                  5.1.22+4.0.11-2                         i386         APC User Cache for PHP
ii  php8.2-cli                                   8.2.7-1~deb12u1                         i386         command-line interpreter for the PHP scripting language
ii  php8.2-common                                8.2.7-1~deb12u1                         i386         documentation, examples and common module for PHP
ii  php8.2-curl                                  8.2.7-1~deb12u1                         i386         CURL module for PHP
ii  php8.2-gd                                    8.2.7-1~deb12u1                         i386         GD module for PHP
ii  php8.2-gmp                                   8.2.7-1~deb12u1                         i386         GMP module for PHP
ii  php8.2-intl                                  8.2.7-1~deb12u1                         i386         Internationalisation module for PHP
ii  php8.2-mbstring                              8.2.7-1~deb12u1                         i386         MBSTRING module for PHP
ii  php8.2-mysql                                 8.2.7-1~deb12u1                         i386         MySQL module for PHP
ii  php8.2-opcache                               8.2.7-1~deb12u1                         i386         Zend OpCache module for PHP
ii  php8.2-pgsql                                 8.2.7-1~deb12u1                         i386         PostgreSQL module for PHP
ii  php8.2-phpdbg                                8.2.7-1~deb12u1                         i386         server-side, HTML-embedded scripting language (PHPDBG binary)
ii  php8.2-readline                              8.2.7-1~deb12u1                         i386         readline module for PHP
ii  php8.2-xml                                   8.2.7-1~deb12u1                         i386         DOM, SimpleXML, XML, and XSL module for PHP


Postgresql:

ii  postgresql-13                                13.11-0+deb11u1                         i386         The World's Most Advanced Open Source Relational Database
ii  postgresql-client-13                         13.11-0+deb11u1                         i386         front-end programs for PostgreSQL 13

Respectfully,

Ken

**Comment by ReimuHakurei** [comment]
I just spun up a Debian 12 VM and installed PHP 8.2 and PostgreSQL 15 from the repos, then installed mailman3-web from the repos as well and was able to edit rows in the users table without issue.

Can you dump the schema of the table in question?

Export -> Structure only -> Show in phpPgAdmin and then paste the result in to this issue.

**Comment by kjohnsonecl** [comment]
Bother.  That means it is probably something I did wrong.  The capability to get that info so simply from phppgadmin is seriously cool.  Per your request:

--
-- PostgreSQL database dump
--

-- Dumped from database version 13.11 (Debian 13.11-0+deb11u1)
-- Dumped by pg_dump version 15.3 (Debian 15.3-0+deb12u1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: mailman3web
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(30) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO mailman3web;

--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: mailman3web
--

CREATE SEQUENCE public.auth_user_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.auth_user_id_seq OWNER TO mailman3web;

--
-- Name: auth_user_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: mailman3web
--

ALTER SEQUENCE public.auth_user_id_seq OWNED BY public.auth_user.id;


--
-- Name: auth_user id; Type: DEFAULT; Schema: public; Owner: mailman3web
--

ALTER TABLE ONLY public.auth_user ALTER COLUMN id SET DEFAULT nextval('public.auth_user_id_seq'::regclass);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: mailman3web
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: mailman3web
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: mailman3web
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- PostgreSQL database dump complete
--

Respectfully,

Ken

**Comment by ReimuHakurei** [comment]
I don't see any reason you should have issues with that schema... It looks identical to what I have working on my end.

Can you try just deleting phpPgAdmin and doing a fresh install and confirm if you still experience the same issue?

**Comment by kjohnsonecl** [comment]
Of course.  I am very thankful for the effort you have made.

To double-check, so I do the correct thing, is the URL given in the first entry the correct one I should use for this test?  Repeated here for convenience:

https://github.com/ReimuHakurei/phpPgAdmin/archive/refs/tags/v7.14.4-mod.tar.gz

Respectfully,

Ken

**Comment by ReimuHakurei** [comment]
Please try the following: https://github.com/ReimuHakurei/phpPgAdmin/archive/refs/tags/v7.14.5-mod.tar.gz
