### ISSUE TITLE
Instructions to allow login access

### ISSUE THREAD

**Issue by clarkk** [ReimuHakurei/phpPgAdmin#13]
Login returns this

`Login disallowed for security reasons.`

I can't find any readme how to allow access to phppgadmin?

**Comment by ReimuHakurei** [comment]
What account are you trying to log in with?

By default, logins to certain system users and accounts without passwords are disabled.

I believe this is "extra login security" in the config file.

**Comment by clarkk** [comment]
Got it. Had to set it to `false`
