### ISSUE TITLE
sql option opens the complete phpPgadmin interface

### ISSUE THREAD

**Issue by u43hvs** [ReimuHakurei/phpPgAdmin#14]
Since a few days my team moved to this version of phpPgadmin
Works great with the new postgres version.
I observe one problem
If i hit the sql menu option (the one left of history) the complete interface of phppgadmin opens in this view
<img width="1207" alt="Schermafbeelding 2023-10-10 om 12 12 48" src="https://github.com/ReimuHakurei/phpPgAdmin/assets/59572403/12176d2a-3935-4538-8d79-8191af9184b6">

**Comment by ReimuHakurei** [comment]
This should in theory be fixed in the new version I just released.

**Comment by u43hvs** [comment]
Ifso you are my hero
