### ISSUE TITLE
pg_connect(): Unable to connect to PostgreSQL server: FATAL: Passwort-Auth failed

### ISSUE THREAD

**Issue by twistios** [ReimuHakurei/phpPgAdmin#17]
I created a new user for my database. When trying to login I get an error-message.

I was able to reproduce it with a super simple user:
Username: "test", password: "test", all rights (superuser, ...)
This is the message I get on a try to sign-in (translated):
```
Warning: pg_connect(): Unable to connect to PostgreSQL server: FATAL: Passwort-Authentification for user test
failed in D:\Programme\XAMPP\phpPgAdmin\libraries\adodb\drivers\adodb-postgres64.inc.php on line 747
```

I already tried to adapt the `pg_hba.conf` but it did not help.
When I change the file to this (I read that changing "local" to "host" might help, maybe because of Windows)
```
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
host   all             all                                     scram-sha-256
# IPv4 local connections:
host    all             all             127.0.0.1/32            scram-sha-256
# IPv6 local connections:
host    all             all             ::1/128                 scram-sha-256
# Allow replication connections from localhost, by a user with the
# replication privilege.
host   replication     all                                     scram-sha-256
host    replication     all             127.0.0.1/32            scram-sha-256
host    replication     all             ::1/128                 scram-sha-256
```
I get a new error:
```
Warning: pg_connect(): Unable to connect to PostgreSQL server: FATAL: could not load D:/Programme/PostgreSQL/16/data/pg_hba.conf
in D:\Programme\XAMPP\phpPgAdmin\libraries\adodb\drivers\adodb-postgres64.inc.php on line 747
```

Using the build-in user "postgres" is working fine (password created on install).

Info:
- Software Version: phpPgAdmin 7.14.6-mod (PHP 8.2.4)
- Server: Apache via XAMPP 8.2.4 on Windows
- PostgreSQL 16

**Comment by ReimuHakurei** [comment]
I would advise checking PostgreSQL's logs (not sure where those are stored on Windows) -- it will likely contain additional details.

**Comment by ReimuHakurei** [comment]
When you created the user, what exact command did you use? If you created it using an MD5 password instead of the newer SCRAM setup, you will need to set pg_hba.conf to md5 instead.

**Comment by ReimuHakurei** [comment]
Update your pg_hba.conf to allow MD5 and restart Postgres and this will likely resolve your issue.

**Comment by twistios** [comment]
I was not able to allow both SCRAM and MD5, but if I only allow MD5 it works.
