### ISSUE TITLE
Estimated number of records is "-1" even if table contains elements

### ISSUE THREAD

**Issue by twistios** [ReimuHakurei/phpPgAdmin#18]
The "Estimated number of records" for my test table is "-1" even if it already contains some rows. 
Also in general "-1" does not make sense as there should be at least "0" records in a table.
I think the minimal requirement for an estimate is to be at least in the range of reasonable values.

Info:
- Software Version: phpPgAdmin 7.14.6-mod (PHP 8.2.4)
- Server: Apache via XAMPP 8.2.4 on Windows
- PostgreSQL Version: 16

**Comment by ReimuHakurei** [comment]
This is just reporting reltuples from pg_class.

Per PostgreSQL documentation: https://www.postgresql.org/docs/current/catalog-pg-class.html

> Number of live rows in the table. This is only an estimate used by the planner. It is updated by [VACUUM](https://www.postgresql.org/docs/current/sql-vacuum.html), [ANALYZE](https://www.postgresql.org/docs/current/sql-analyze.html), and a few DDL commands such as [CREATE INDEX](https://www.postgresql.org/docs/current/sql-createindex.html). If the table has never yet been vacuumed or analyzed, reltuples contains -1 indicating that the row count is unknown.

If you would like to update this value, just ANALYZE the table in question.
