### ISSUE TITLE
No value shown for "last value" for sequences

### ISSUE THREAD

**Issue by twistios** [ReimuHakurei/phppgadmin#19]
The "Last value" field for sequences does not contain a value/does not get updated. As there is no way to "ANALYSE" this, I am not able to update it myself.
The internal value gets updated as the sequence can be used as a generator for ids in tables.

Info:
- Software Version: phpPgAdmin  (commit [bb031d0](https://github.com/ReimuHakurei/phpPgAdmin/commit/bb031d0a950ae02ff19a2882de92a86002a67c9b)) (PHP 8.2.4)
- Server: Apache via XAMPP 8.2.4 on Windows
- PostgreSQL Version: 16

**Comment by ReimuHakurei** [comment]
Should be fixed in the latest commit.
