### ISSUE TITLE
appVersion suffix

### ISSUE THREAD

**Issue by computersalat** [ReimuHakurei/phpPgAdmin#20]
Why did you add a suffix **_-mod_** to **_$appVersion_** ?

**Comment by ReimuHakurei** [comment]
To distinguish from any potential future official releases. 

Probably pointless by now, but at the time this fork was started, it was assumed the official project would eventually revive again, as it did multiple times after prior periods of inactivity. As such, the suffix was added to prevent any possible version conflicts.
