### ISSUE TITLE
php 8.3.9 shows a lot of warnings, deprecated and broken functions.

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [ReimuHakurei/phpPgAdmin#26]
Anyone is using php 8.3.9 to confirm it needs some fixes?

**Comment by ReimuHakurei** [comment]
Can you provide some examples of the messages you are receiving? Thus far I do not observe any obvious issues on PHP 8.3.6 as shipped in Ubuntu 24.04.

**Comment by ROBERT-MCDOWELL** [comment]
sorry I mixed a phpPgAdmin from the original author with your repo.
everything is ok with 8.3.11 (some little glitch about some SQL request of deprecated functions though)
closing the issue
