### ISSUE TITLE
Links on introduction page

### ISSUE THREAD

**Issue by danielmarschall** [ReimuHakurei/phpPgAdmin#27]
[At the introduction page](https://github.com/ReimuHakurei/phpPgAdmin/blob/master/intro.php), there are two links which I think should be changed.

* The home of phpPgAdmin links to sourceforge, which is very outdated. It should be either the original GitHub repo, or better it should be https://github.com/ReimuHakurei/ , since the original authors don't maintain the project, so this fork is probably the best source.

* The "report a bug" link goes to http://sourceforge.net/tracker/?group_id=37132&atid=418980 , but this is VERY outdated, because it has been moved to GitHub, AND the original authors don't fix anything since 2020. So, I think the correct link would be https://github.com/ReimuHakurei/phpPgAdmin/issues
(Changing also has the advantage that the fork can be detected; this would be important for my [Nagios plugin for checking for new phpPgAdmin updates](https://github.com/danielmarschall/vnag/blob/10d7029afdf059803f35a2fb794b11ddc96690c5/src/plugins/phppgadmin_version/PhpPgAdminVersionCheck.class.php#L55).)

* I see the link "Selenium tests" which is dead. I don't know why such a link exists in the first place, because tests is not something that the end user should see, but in any case, I think this should be only shown if the tests folder actually exists and otherwise be hidden.

What do you think?

**Comment by ReimuHakurei** [comment]
Sounds good to me -- I'll also remove the "View online FAQ" link, as it is also dead.
